### ISSUE TITLE
java.lang.RuntimeException: Cannot make calls to a recycled instance!

### ISSUE THREAD

**Issue by L-kaxy** [peng8350/JPTabBar#32]
Caused by: java.lang.RuntimeException: Cannot make calls to a recycled instance!
at android.content.res.TypedArray.getColor(TypedArray.java:459)
at com.jpeng.jptabbar.JPTabBar.initFromAttribute(JPTabBar.java:170)
at com.jpeng.jptabbar.JPTabBar.generate(JPTabBar.java:506)

机型：
Android: 8.1.0
Manufacturer: HUAWEI
Model: CLT-AL00

这个是用户使用时触发奔溃的日志，也就这个安卓8.1.0的触发了

**Comment by peng8350** [comment]
这个问题是一开始初始化界面还是经过生命周期的改变(比如转屏)造成的异常?

**Comment by L-kaxy** [comment]
应该不是转屏导致的，app全局 screenOrientation="portrait" 限制竖屏了

机型：
Android: 7.0
Manufacturer: GIONEE
Model: GIONEE S10

昨天又多了一个机型出现这种情况，只触发了一次。
CLT-AL00触发过两次。

都是在主界面（使用JPTabbar）启动另一个activity时触发的。

**Comment by github2603006784** [comment]
分屏模式 然后拉动那个边界线 就会触发这个bug

**Comment by usheweb** [comment]
在Fragment中使用，通过Navigation.findNavController(mRootView).navigateUp(); 进行切换Fragment，返回就会触发这个异常，navigateUp()的时候，Jptabbar所在的Fragment已经销毁了，返回Jptabbar所在的Fragment时，重新触发了onCreateView，就出现了Cannot make calls to a recycled instance
